// Faithful port of QRScannerPairingValidator.swift.
// Accepts: raw JSON pairing payloads, AGNT1: base64url-encoded paste tokens, and short pairing codes.
// Web build can't (yet) scan a QR with the camera, so users paste the JSON payload the bridge
// prints alongside the QR (the bridge does not emit a prefixed token; the AGNT1: path is a paste
// convenience). RMX1: is the legacy upstream prefix, still accepted for back-compat.

import { PAIRING_QR_VERSION } from "../crypto";

const PAIRING_CODE_PREFIX = "AGNT1:";
const LEGACY_PAIRING_CODE_PREFIX = "RMX1:";
const PAIRING_CODE_PREFIXES = [PAIRING_CODE_PREFIX, LEGACY_PAIRING_CODE_PREFIX];
const SHORT_CODE_PATTERN = /^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8,12}$/;
const PAIRING_KEYS = ["relay", "sessionId", "macDeviceId", "macIdentityPublicKey", "expiresAt", "v"] as const;
// Mirrors codexSecureClockSkewToleranceSeconds in iOS (60s).
const PAIRING_CLOCK_SKEW_TOLERANCE_MS = 60_000;

export interface PairingPayload {
  v: number;
  relay: string;
  sessionId: string;
  macDeviceId: string;
  macIdentityPublicKey: string;
  expiresAt: number;
}

export type PairingValidationResult =
  | { kind: "payload"; payload: PairingPayload }
  | { kind: "shortCode"; code: string }
  | { kind: "bridgeUpdateRequired"; message: string }
  | { kind: "error"; message: string };

export function validatePairingInput(raw: string, now: Date = new Date()): PairingValidationResult {
  const trimmed = raw.trim();
  if (!trimmed) return error("Paste the pairing payload printed under the QR code.");

  const normalizedShort = trimmed.toUpperCase().replace(/[\s-]/g, "");
  if (SHORT_CODE_PATTERN.test(normalizedShort)) {
    return { kind: "shortCode", code: normalizedShort };
  }

  const matchedPrefix = PAIRING_CODE_PREFIXES.find((prefix) => trimmed.startsWith(prefix));
  const candidateJson = matchedPrefix ? decodePairingToken(trimmed, matchedPrefix) : trimmed;
  if (!candidateJson) return error("This pairing code is unreadable. Copy it again from the bridge.");

  let parsed: unknown;
  try {
    parsed = JSON.parse(candidateJson);
  } catch {
    return error("Not a valid pairing payload. Make sure you copied the full text under the QR.");
  }

  if (!isPairingShape(parsed)) {
    return error("Not a valid pairing payload. Make sure you copied the full text under the QR.");
  }

  if (parsed.v !== PAIRING_QR_VERSION) {
    return looksLikeOldPairing(parsed)
      ? bridgeUpdate("This QR was generated by a different agnt version. Update the npm package on your computer.")
      : error("Unsupported pairing payload version.");
  }

  if (!parsed.relay.trim()) return error("Pairing payload is missing the relay URL.");
  if (!parsed.sessionId.trim()) return error("Pairing payload is missing the session ID.");
  if (!parsed.macDeviceId.trim()) return error("Pairing payload is missing the Mac device ID.");
  if (!parsed.macIdentityPublicKey.trim()) return error("Pairing payload is missing the Mac identity key.");

  const expiresAtMs = Number(parsed.expiresAt);
  if (!Number.isFinite(expiresAtMs)) return error("Pairing payload has an invalid expiry.");
  if (expiresAtMs + PAIRING_CLOCK_SKEW_TOLERANCE_MS < now.getTime()) {
    return error("This pairing code has expired. Generate a fresh one from the bridge.");
  }

  return { kind: "payload", payload: parsed };
}

function decodePairingToken(token: string, prefix: string): string | null {
  const encoded = token.slice(prefix.length).replace(/-/g, "+").replace(/_/g, "/");
  const padding = (4 - (encoded.length % 4)) % 4;
  try {
    const binary = atob(encoded + "=".repeat(padding));
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
    return new TextDecoder().decode(bytes);
  } catch {
    return null;
  }
}

function isPairingShape(value: unknown): value is PairingPayload {
  if (!value || typeof value !== "object") return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v.v === "number" &&
    typeof v.relay === "string" &&
    typeof v.sessionId === "string" &&
    typeof v.macDeviceId === "string" &&
    typeof v.macIdentityPublicKey === "string" &&
    typeof v.expiresAt === "number"
  );
}

function looksLikeOldPairing(value: unknown): boolean {
  if (!value || typeof value !== "object") return false;
  const keys = new Set(Object.keys(value as Record<string, unknown>));
  return PAIRING_KEYS.some((key) => keys.has(key));
}

function error(message: string): PairingValidationResult {
  return { kind: "error", message };
}

function bridgeUpdate(message: string): PairingValidationResult {
  return { kind: "bridgeUpdateRequired", message };
}
