// Per-turn token usage extractor. The bridge's `thread/tokenUsage/updated`
// event carries Claude's full usage breakdown (input / output / cached /
// cost). We normalize it here so the assistant-row chip can show
// "1.2k tokens · $0.018" without each component re-implementing parsing.
//
// The extractor accepts the loosely-typed JSON-RPC params and returns null
// when the payload is missing or unparseable — callers should treat null
// as "no usage data this turn", not "zero tokens".

export interface TurnTokenUsage {
  /** Combined input + cached input tokens billed for the turn. */
  inputTokens: number;
  /** Tokens generated by the model. */
  outputTokens: number;
  /** Cached prompt tokens (Claude's prompt cache). 0 if unavailable. */
  cachedInputTokens: number;
  /** USD cost as reported by the provider. `null` when not surfaced
   *  (e.g. opencode / codex) — callers should hide the price chip. */
  totalCostUsd: number | null;
}

/** Sum of input + output for a quick "total" display. */
export function totalTokens(usage: TurnTokenUsage): number {
  return usage.inputTokens + usage.outputTokens;
}

/** Format a token count compactly: 1234 → "1.2k", 12_345 → "12k". */
export function formatTokens(count: number): string {
  if (!Number.isFinite(count) || count <= 0) return "0";
  if (count < 1000) return String(count);
  if (count < 100_000) return `${(count / 1000).toFixed(1).replace(/\.0$/, "")}k`;
  if (count < 1_000_000) return `${Math.round(count / 1000)}k`;
  return `${(count / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`;
}

/** Format a USD cost: < $0.01 → "<$0.01"; otherwise four-sig-fig. */
export function formatCostUsd(cost: number): string {
  if (!Number.isFinite(cost) || cost <= 0) return "$0";
  if (cost < 0.01) return "<$0.01";
  if (cost < 1) return `$${cost.toFixed(3)}`;
  return `$${cost.toFixed(2)}`;
}

const NESTED_KEYS = ["tokenUsage", "usage", "info"] as const;

/** Pluck a numeric value at any of `keys`, falling back to nested
 *  containers (`tokenUsage`, `usage`, `info`). Returns null when none of
 *  them resolve to a finite number. */
function firstNumber(payload: unknown, keys: readonly string[]): number | null {
  if (!payload || typeof payload !== "object") return null;
  const obj = payload as Record<string, unknown>;
  for (const key of keys) {
    const value = obj[key];
    if (typeof value === "number" && Number.isFinite(value)) return value;
  }
  for (const nested of NESTED_KEYS) {
    const inner = obj[nested];
    if (inner && typeof inner === "object") {
      const v = firstNumber(inner, keys);
      if (v !== null) return v;
    }
  }
  return null;
}

export function extractTurnTokenUsage(payload: unknown): TurnTokenUsage | null {
  if (!payload || typeof payload !== "object") return null;
  const inputTokens = firstNumber(payload, ["inputTokens", "input_tokens"]) ?? 0;
  const outputTokens = firstNumber(payload, ["outputTokens", "output_tokens"]) ?? 0;
  if (inputTokens === 0 && outputTokens === 0) return null;
  const cachedInputTokens =
    firstNumber(payload, ["cachedInputTokens", "cached_input_tokens", "cache_read_input_tokens"]) ?? 0;
  const totalCostUsd = firstNumber(payload, ["totalCostUsd", "total_cost_usd"]);
  return { inputTokens, outputTokens, cachedInputTokens, totalCostUsd };
}
