package com.dotbrains.agnt.mobile.data

import com.dotbrains.agnt.mobile.core.model.AGNT_PAIRING_QR_VERSION
import com.dotbrains.agnt.mobile.core.model.AGNT_SECURE_CLOCK_SKEW_TOLERANCE_SECONDS
import com.dotbrains.agnt.mobile.core.model.CodexPairingQRPayload
import com.dotbrains.agnt.mobile.core.transport.validateRelayUrl
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import okhttp3.HttpUrl
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.Base64

private val pairingJson =
    Json {
        ignoreUnknownKeys = true
        coerceInputValues = true
    }

private const val QR_SCANNER_BRIDGE_UPDATE_COMMAND = "bun install -g @dotbrains/agnt"
private val pairingJsonMediaType = "application/json; charset=utf-8".toMediaType()
private const val MAX_PAIRING_FIELD_LENGTH = 256
private const val ED25519_PUBLIC_KEY_BYTES = 32
private const val QR_SCANNER_PAIRING_CODE_PREFIX = "RMX1:"
private val qrScannerShortCodeRegex = Regex("^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{8,12}$")
private val pairingIdRegex = Regex("^[A-Za-z0-9._:-]{1,$MAX_PAIRING_FIELD_LENGTH}$")

@Serializable
private data class PairingCodeResolveRequest(
    val code: String,
)

@Serializable
private data class PairingCodeResolveResponse(
    val ok: Boolean = false,
    val v: Int? = null,
    val sessionId: String? = null,
    val macDeviceId: String? = null,
    val macIdentityPublicKey: String? = null,
    val expiresAt: Long? = null,
    val error: String? = null,
    val code: String? = null,
)

sealed class QrPairingValidationResult {
    data class Success(
        val payload: CodexPairingQRPayload,
    ) : QrPairingValidationResult()

    data class ShortCode(
        val code: String,
    ) : QrPairingValidationResult()

    data class ScanError(
        val message: String,
    ) : QrPairingValidationResult()

    data class BridgeUpdateRequired(
        val title: String,
        val message: String,
        val command: String = QR_SCANNER_BRIDGE_UPDATE_COMMAND,
    ) : QrPairingValidationResult()
}

/**
 * Classifies scanned QR payloads (parity with [QRScannerPairingValidator.swift](CodexMobile/CodexMobile/Views/QRScannerPairingValidator.swift)).
 */
fun validatePairingQrCode(
    code: String,
    nowEpochMillis: Long = System.currentTimeMillis(),
): QrPairingValidationResult {
    val trimmed = code.trim()
    val normalizedShortCode = normalizeShortPairingCode(trimmed)
    if (qrScannerShortCodeRegex.matches(normalizedShortCode)) {
        return QrPairingValidationResult.ShortCode(normalizedShortCode)
    }

    val normalizedCode =
        if (trimmed.startsWith(QR_SCANNER_PAIRING_CODE_PREFIX)) {
            decodePasteablePairingCode(trimmed)
                ?: return QrPairingValidationResult.ScanError(
                    "This pairing code is unreadable. Copy it again from the computer bridge.",
                )
        } else {
            trimmed
        }

    val payload =
        runCatching {
            pairingJson.decodeFromString<CodexPairingQRPayload>(normalizedCode)
        }.getOrNull()

    if (payload != null) {
        if (payload.v != AGNT_PAIRING_QR_VERSION) {
            return QrPairingValidationResult.BridgeUpdateRequired(
                title = "Update agnt on your computer before scanning",
                message =
                    "This QR code was generated by a different agnt npm version. " +
                        "Update the package on your computer to the latest release before scanning a new QR code.",
            )
        }
        if (payload.relay.trim().isEmpty()) {
            return QrPairingValidationResult.ScanError(
                "QR code is missing pairing route metadata. Re-generate the code from the bridge.",
            )
        }
        if (payload.sessionId.trim().isEmpty()) {
            return QrPairingValidationResult.ScanError(
                "QR code is missing the session ID. Re-generate the code from the bridge.",
            )
        }
        validatePairingFields(
            relay = payload.relay,
            sessionId = payload.sessionId,
            macDeviceId = payload.macDeviceId,
            macIdentityPublicKey = payload.macIdentityPublicKey,
        )?.let { return it }
        val skewMillis = (AGNT_SECURE_CLOCK_SKEW_TOLERANCE_SECONDS * 1000).toLong()
        if (nowEpochMillis > payload.expiresAt + skewMillis) {
            return QrPairingValidationResult.ScanError(
                "This pairing QR code has expired. Generate a new one from the Mac bridge.",
            )
        }
        return QrPairingValidationResult.Success(payload)
    }

    if (looksLikeAgntPairingPayload(normalizedCode)) {
        return QrPairingValidationResult.BridgeUpdateRequired(
            title = "Update agnt on your computer before scanning",
            message =
                "This QR code looks like it came from an older agnt bridge. " +
                    "Update the npm package on your computer to the latest release before scanning a new QR code.",
        )
    }

    return QrPairingValidationResult.ScanError(
        "Not a valid secure pairing code. Make sure you're scanning a QR from the latest agnt bridge.",
    )
}

suspend fun resolvePairingCode(
    httpClient: OkHttpClient,
    relayUrl: String,
    code: String,
    nowEpochMillis: Long = System.currentTimeMillis(),
): QrPairingValidationResult =
    withContext(Dispatchers.IO) {
        val normalizedCode = normalizeShortPairingCode(code)
        if (normalizedCode.isEmpty()) {
            return@withContext QrPairingValidationResult.ScanError("Enter the pairing code from your desktop.")
        }

        val endpoint =
            pairingCodeResolveRoute(relayUrl)
                ?: return@withContext QrPairingValidationResult.ScanError(
                    "Pairing code resolver is unavailable. Scan the QR once, then try code pairing again.",
                )
        val body =
            pairingJson
                .encodeToString(PairingCodeResolveRequest(normalizedCode))
                .toRequestBody(pairingJsonMediaType)
        val request =
            Request
                .Builder()
                .url(endpoint.resolveUrl)
                .post(body)
                .build()

        runCatching {
            httpClient.newCall(request).execute().use { response ->
                val responseBody = response.body?.string().orEmpty()
                val decoded =
                    runCatching {
                        pairingJson.decodeFromString<PairingCodeResolveResponse>(responseBody)
                    }.getOrNull()

                if (!response.isSuccessful || decoded?.ok != true) {
                    if (decoded?.code == "pairing_code_expired") {
                        return@withContext QrPairingValidationResult.ScanError(
                            "This pairing code has expired. Generate a new one from the desktop bridge.",
                        )
                    }
                    if (decoded?.code == "pairing_code_unavailable") {
                        return@withContext QrPairingValidationResult.ScanError(
                            "That pairing code is not available right now. Make sure your desktop bridge is running and try again.",
                        )
                    }
                    if (response.code == 404) {
                        return@withContext QrPairingValidationResult.ScanError(
                            "This relay does not support pairing codes yet. Scan the QR code instead.",
                        )
                    }
                    return@withContext QrPairingValidationResult.ScanError(
                        decoded?.error ?: "Pairing code unavailable. Generate a fresh code from your desktop.",
                    )
                }

                val version = decoded.v
                if (version != AGNT_PAIRING_QR_VERSION) {
                    return@withContext QrPairingValidationResult.BridgeUpdateRequired(
                        title = "Update agnt on your desktop before pairing",
                        message =
                            "This pairing code was generated by a different agnt bridge version. " +
                                "Update the desktop bridge and generate a new code.",
                    )
                }

                val sessionId = decoded.sessionId?.trim().orEmpty()
                val macDeviceId = decoded.macDeviceId?.trim().orEmpty()
                val macIdentityPublicKey = decoded.macIdentityPublicKey?.trim().orEmpty()
                val expiresAt = decoded.expiresAt
                if (
                    sessionId.isEmpty() ||
                    macDeviceId.isEmpty() ||
                    macIdentityPublicKey.isEmpty() ||
                    expiresAt == null
                ) {
                    return@withContext QrPairingValidationResult.ScanError(
                        "The relay returned incomplete pairing metadata. Generate a new code from the desktop bridge.",
                    )
                }
                val resolvedRelay = endpoint.relayUrl
                validatePairingFields(
                    relay = resolvedRelay,
                    sessionId = sessionId,
                    macDeviceId = macDeviceId,
                    macIdentityPublicKey = macIdentityPublicKey,
                )?.let { return@withContext it }

                val skewMillis = (AGNT_SECURE_CLOCK_SKEW_TOLERANCE_SECONDS * 1000).toLong()
                if (nowEpochMillis > expiresAt + skewMillis) {
                    return@withContext QrPairingValidationResult.ScanError(
                        "This pairing code has expired. Generate a new one from the desktop bridge.",
                    )
                }

                QrPairingValidationResult.Success(
                    CodexPairingQRPayload(
                        v = version,
                        relay = resolvedRelay,
                        sessionId = sessionId,
                        macDeviceId = macDeviceId,
                        macIdentityPublicKey = macIdentityPublicKey,
                        expiresAt = expiresAt,
                    ),
                )
            }
        }.getOrElse { error ->
            QrPairingValidationResult.ScanError(
                error.message ?: "Could not reach the relay for this pairing code. Try again or scan the QR code.",
            )
        }
    }

fun normalizeShortPairingCode(code: String): String =
    code
        .trim()
        .uppercase()
        .replace("-", "")
        .replace(" ", "")

// Reuses the QR validator for manual entry by decoding the bridge's paste-friendly token back into JSON.
private fun decodePasteablePairingCode(code: String): String? {
    val encoded =
        code
            .drop(QR_SCANNER_PAIRING_CODE_PREFIX.length)
            .replace("-", "+")
            .replace("_", "/")
    val padding = (4 - (encoded.length % 4)) % 4
    val padded = encoded + "=".repeat(padding)
    val decoded =
        runCatching { Base64.getDecoder().decode(padded) }.getOrNull()
            ?: return null
    return decoded.toString(Charsets.UTF_8)
}

private fun looksLikeAgntPairingPayload(raw: String): Boolean {
    val obj =
        runCatching {
            pairingJson.parseToJsonElement(raw).jsonObject
        }.getOrNull() ?: return false
    val pairingKeys =
        setOf(
            "relay",
            "sessionId",
            "macDeviceId",
            "macIdentityPublicKey",
            "expiresAt",
            "v",
        )
    return obj.keys.any { it in pairingKeys }
}

private fun validatePairingFields(
    relay: String,
    sessionId: String,
    macDeviceId: String,
    macIdentityPublicKey: String,
): QrPairingValidationResult.ScanError? {
    val fields = listOf(relay, sessionId, macDeviceId, macIdentityPublicKey)
    if (fields.any { it.length > MAX_PAIRING_FIELD_LENGTH || containsUnsafePairingChars(it) }) {
        return QrPairingValidationResult.ScanError(
            "Pairing metadata has invalid characters or is too large. Generate a new code from the desktop bridge.",
        )
    }
    if (!pairingIdRegex.matches(sessionId) || !pairingIdRegex.matches(macDeviceId)) {
        return QrPairingValidationResult.ScanError(
            "Pairing metadata has an invalid identifier. Generate a new code from the desktop bridge.",
        )
    }
    val keyBytes =
        runCatching { Base64.getDecoder().decode(macIdentityPublicKey) }.getOrNull()
            ?: return QrPairingValidationResult.ScanError(
                "Pairing metadata has an invalid Mac identity key. Generate a new code from the desktop bridge.",
            )
    if (keyBytes.size != ED25519_PUBLIC_KEY_BYTES) {
        return QrPairingValidationResult.ScanError(
            "Pairing metadata has an invalid Mac identity key. Generate a new code from the desktop bridge.",
        )
    }
    if (validateRelayUrl(relay, requireWebSocketScheme = true) == null) {
        return QrPairingValidationResult.ScanError(
            "Pairing metadata has an invalid or insecure relay URL. Use a local relay or a secure wss:// relay.",
        )
    }
    return null
}

private fun containsUnsafePairingChars(value: String): Boolean = value.any { it.isISOControl() || it.isWhitespace() }

private data class PairingCodeResolveRoute(
    val resolveUrl: HttpUrl,
    val relayUrl: String,
)

// Handles relay URLs that already include a /relay suffix (e.g. ws://host:9000/relay)
// by stripping it before appending /v1/pairing/code/resolve. validateRelayUrl already
// surfaces the matching websocket URL the resolved code should pair against.
private fun pairingCodeResolveRoute(rawRelayUrl: String): PairingCodeResolveRoute? {
    val validation = validateRelayUrl(rawRelayUrl) ?: return null
    val pathSegments = validation.httpUrl.pathSegments.filter { it.isNotEmpty() }
    val resolveSegments =
        if (pathSegments.lastOrNull() == "relay") {
            pathSegments.dropLast(1) + listOf("v1", "pairing", "code", "resolve")
        } else {
            listOf("v1", "pairing", "code", "resolve")
        }
    val resolveUrl =
        validation.httpUrl
            .newBuilder()
            .encodedPath("/" + resolveSegments.joinToString("/"))
            .query(null)
            .fragment(null)
            .build()
    return PairingCodeResolveRoute(resolveUrl = resolveUrl, relayUrl = validation.websocketUrl)
}
